/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as homeIndexImport } from './routes/(home)/index'
import { Route as restaurantsRestaurantsImport } from './routes/(restaurants)/restaurants'
import { Route as addrestaurantCreateImport } from './routes/(add restaurant)/create'
import { Route as authregisterRegisterImport } from './routes/(auth)/(register)/register'
import { Route as authloginLoginImport } from './routes/(auth)/(login)/login'

// Create/Update Routes

const homeIndexRoute = homeIndexImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const restaurantsRestaurantsRoute = restaurantsRestaurantsImport.update({
  id: '/(restaurants)/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRoute,
} as any)

const addrestaurantCreateRoute = addrestaurantCreateImport.update({
  id: '/(add restaurant)/create',
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const authregisterRegisterRoute = authregisterRegisterImport.update({
  id: '/(auth)/(register)/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const authloginLoginRoute = authloginLoginImport.update({
  id: '/(auth)/(login)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(add restaurant)/create': {
      id: '/(add restaurant)/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof addrestaurantCreateImport
      parentRoute: typeof rootRoute
    }
    '/(restaurants)/restaurants': {
      id: '/(restaurants)/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof restaurantsRestaurantsImport
      parentRoute: typeof rootRoute
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/(login)/login': {
      id: '/(auth)/(login)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authloginLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/(register)/register': {
      id: '/(auth)/(register)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authregisterRegisterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/create': typeof addrestaurantCreateRoute
  '/restaurants': typeof restaurantsRestaurantsRoute
  '/': typeof homeIndexRoute
  '/login': typeof authloginLoginRoute
  '/register': typeof authregisterRegisterRoute
}

export interface FileRoutesByTo {
  '/create': typeof addrestaurantCreateRoute
  '/restaurants': typeof restaurantsRestaurantsRoute
  '/': typeof homeIndexRoute
  '/login': typeof authloginLoginRoute
  '/register': typeof authregisterRegisterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(add restaurant)/create': typeof addrestaurantCreateRoute
  '/(restaurants)/restaurants': typeof restaurantsRestaurantsRoute
  '/(home)/': typeof homeIndexRoute
  '/(auth)/(login)/login': typeof authloginLoginRoute
  '/(auth)/(register)/register': typeof authregisterRegisterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/create' | '/restaurants' | '/' | '/login' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/create' | '/restaurants' | '/' | '/login' | '/register'
  id:
    | '__root__'
    | '/(add restaurant)/create'
    | '/(restaurants)/restaurants'
    | '/(home)/'
    | '/(auth)/(login)/login'
    | '/(auth)/(register)/register'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  addrestaurantCreateRoute: typeof addrestaurantCreateRoute
  restaurantsRestaurantsRoute: typeof restaurantsRestaurantsRoute
  homeIndexRoute: typeof homeIndexRoute
  authloginLoginRoute: typeof authloginLoginRoute
  authregisterRegisterRoute: typeof authregisterRegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  addrestaurantCreateRoute: addrestaurantCreateRoute,
  restaurantsRestaurantsRoute: restaurantsRestaurantsRoute,
  homeIndexRoute: homeIndexRoute,
  authloginLoginRoute: authloginLoginRoute,
  authregisterRegisterRoute: authregisterRegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(add restaurant)/create",
        "/(restaurants)/restaurants",
        "/(home)/",
        "/(auth)/(login)/login",
        "/(auth)/(register)/register"
      ]
    },
    "/(add restaurant)/create": {
      "filePath": "(add restaurant)/create.tsx"
    },
    "/(restaurants)/restaurants": {
      "filePath": "(restaurants)/restaurants.tsx"
    },
    "/(home)/": {
      "filePath": "(home)/index.tsx"
    },
    "/(auth)/(login)/login": {
      "filePath": "(auth)/(login)/login.tsx"
    },
    "/(auth)/(register)/register": {
      "filePath": "(auth)/(register)/register.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
